### ISSUE TITLE
SyntaxError in FatSegNet running on CPU Docker

### ISSUE THREAD

**Issue by AlbCol** [reuter-lab/FatSegNet#12]
**Dear FatSegNet developers,**

**When trying to run FatSegNet using CPU docker image with below command.**

docker run -it --rm --name fatsegnet -u $(id -u) -v //c/Users/PWS1/Desktop/dataset/:/tool/Data -v //c/Users/PWS1/Desktop/output/:/tool/Output  adipose_tool:cpu_v1

**I am facing this issue:**

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "./run_FatSegNet.py", line 8, in <module>
    from Code.adipose_pipeline import run_adipose_pipeline
  File "/tool/Code/adipose_pipeline.py", line 27, in <module>
    from Code.utilities.metrics import calculate_statistics_v2
  File "/tool/Code/utilities/metrics.py", line 17, in <module>
    from skimage.measure import perimeter
  File "/usr/local/lib/python3.5/dist-packages/skimage/__init__.py", line 135, in <module>
    from .data import data_dir
  File "/usr/local/lib/python3.5/dist-packages/skimage/data/__init__.py", line 13, in <module>
    from ..io import imread, use_plugin
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 91, in reset_plugins
    _load_preferred_plugins()
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 71, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 83, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 254, in use_plugin
    _load(name)
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/manage_plugins.py", line 298, in _load
    fromlist=[modname])
  File "/usr/local/lib/python3.5/dist-packages/skimage/io/_plugins/imageio_plugin.py", line 3, in <module>
    from imageio import imread, imsave
  File "/usr/local/lib/python3.5/dist-packages/imageio/__init__.py", line 21, in <module>
    from . import config
  File "/usr/local/lib/python3.5/dist-packages/imageio/config/__init__.py", line 1, in <module>
    from .extensions import known_extensions
  File "/usr/local/lib/python3.5/dist-packages/imageio/config/extensions.py", line 828
    _extension_dict: Dict[str, List[FileExtension]] = dict()
                   ^
SyntaxError: invalid syntax

**Any leads would be truly appreciated!**
**Thanks!**

**Comment by santiestrada32** [comment]
Which operating system are you running the docker?

**Comment by AlbCol** [comment]
I'm using WSL2 on a Windows10 PC.
I tried Ubuntu 16.04, 18.04 and 20.04 and the message is always the same.

**Comment by AlbCol** [comment]
Dear @santiestrada32,
Do you have any suggestions as to why this error occurred?

Many thanks

**Comment by santiestrada32** [comment]
There is an error in the skiimage library you can try to set up a newer version of the library in docker image creation.  We are moving our all code to pytorch you can try our pytorch version https://github.com/reuter-lab/FatSegNet_pytorch.

**Comment by AlbCol** [comment]
I used the pytorch version and it works.

Thanks!
