### ISSUE TITLE
ImageFileError

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [reuter-lab/FatSegNet#5]
Hi,
When trying to run  paper implementation using GPU compatible docker image with below command.
 **nvidia-docker run --rm -v ~/Akhila/FatSegNet/example_data_folder/:/tool/Data -v ~/Akhila/FatSegNet/temp/:/tool/Output adipose_tool:v1 -loc** 
I am facing below issue.
````
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "./run_FatSegNet.py", line 168, in <module>
    run_fatsegnet(args,FLAGS)
  File "./run_FatSegNet.py", line 135, in run_fatsegnet
    run_adipose_pipeline(args=args, flags=FLAGS, save_path=save_path,data_path=path[0],id=str(id))
  File "/tool/Code/adipose_pipeline.py", line 191, in run_adipose_pipeline
    fat_img = nib.load(fat_file[0])
  File "/usr/local/lib/python3.5/dist-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/tool/Data/subject_1/FatImaging_F.nii.gz"
/tool/Data/participants.csv
------------------------------
 Loading Subject
subject_1
------------------------------
Loading Fat Image
/tool/Data/subject_1/FatImaging_F.nii.gz
````
any leads would be so helpful.

**Comment by santiestrada32** [comment]
Hi,
You have to provided your own fat images, the images in the folder are just illustrative of how the folder has to be organized.

**Comment by AkhilaPerumalla123** [comment]
Thank you for the reply. Will check with other data.
